# Generated by Django 5.2.4 on 2026-01-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_alter_songmodel_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistmodel',
            name='img',
            field=models.ImageField(default=1, upload_to='artist_model_thumbnails'),
            preserve_default=False,
        ),
    ]
